### ISSUE TITLE
Editing database name in the Database management section doesn't have any effect

### ISSUE THREAD

**Issue by vbarrera** [snowformatics/BlasterQt#10]
Hi.

Editing and changing the name in the Database management section doesn't have any effect. Although the name changes in that section, the other tools doesn't seem to detect the change.

Best.

**Comment by snowformatics** [comment]
Fixed with
https://github.com/snowformatics/BlasterQt/commit/01a61ad2602ae5fceea6a3424bf6eb4390fa907b

Actually editing database name should be enabled

**Comment by vbarrera** [comment]
No longer possible to change database name. 
Is that the desired behavior? Although not vital, changing the database name might be useful.

**Comment by snowformatics** [comment]
We discussed this issue and some user prefer to enabled this function because they reported a renaming by mistake. Hope that's ok, otherwise let me know.
