### ISSUE TITLE
Missing documentation

### ISSUE THREAD

**Issue by vbarrera** [snowformatics/BlasterQt#11]
Hi.

Although the help section is quite helpful, some tools lack any information. For example, for the format converter tools there's no information on how to use the multi/single FASTA converters. It isn't clear how to organize the files and folders to obtain the desired result. 

Best.

**Comment by snowformatics** [comment]
The documentation including screenshots were updated. 
http://labtools.ipk-gatersleben.de/help/BlasterQt/BlasterQt.pdf

**Comment by vbarrera** [comment]
Thanks.
Updates would be also needed to the help menu. 
![help_menu](https://user-images.githubusercontent.com/14740681/68088441-5126ee00-fe2d-11e9-82f8-68a32640e5c3.png)
Best

**Comment by snowformatics** [comment]
Of course, done.
