### ISSUE TITLE
Uninstaller leaves some files behind

### ISSUE THREAD

**Issue by vbarrera** [snowformatics/BlasterQt#16]
Improvement:
For cleaner uninstall.
When using the uninstaller "unins000.exe", some files are left in C:\Users\User\AppData\Local\BlasterQt

Best,

**Comment by snowformatics** [comment]
Thanks for your comment. We decided to leave the databases and the log files to easily install new versions without to create again the databases. This was a request from several users. 

However it's not a problem to create an uninstaller which deletes the database files for the publication (deleting all files is not recommended by InnoSetup see http://www.jrsoftware.org/ishelp/index.php?topic=uninstalldeletesection.

Just let me know what you prefer.

**Comment by vbarrera** [comment]
I agree with the explanation. 
Thanks.
