### ISSUE TITLE
Multifasta file to Single Fasta Files, no headers

### ISSUE THREAD

**Issue by vbarrera** [snowformatics/BlasterQt#19]
Headers are lost from multifasta file to single fasta files.

[test_multi.zip](https://github.com/snowformatics/BlasterQt/files/3801801/test_multi.zip)

Best.

**Comment by snowformatics** [comment]
Fixed in BlasterQtv1.4

**Comment by snowformatics** [comment]
Fixed with BlasterQtv1.4
