### ISSUE TITLE
Databases names ignore everything after "."

### ISSUE THREAD

**Issue by vbarrera** [snowformatics/BlasterQt#9]
Hi.

When creating new databases if the name includes ".", everything after is ignored.

For example:
HS.GRh38 becomes HS.

I'd recommend either to indicate it in the documentation or parse it somehow.

Best.

**Comment by snowformatics** [comment]
Fixed with
https://github.com/snowformatics/BlasterQt/commit/4dbbeebb990147d1951ba7f4d15d6254856b9f94
